### ISSUE TITLE
Excel Formating

### ISSUE THREAD

**Issue by vijaysiva** [DataTables/TableTools#73]
In Excel export i cant able to format the excel cells like headers with bold, coloring etc... And Another while exporting excel cells are merged how to set width of columns

**Comment by DataTables** [comment]
There are a [number of discussions on this topic in the DataTables forums](http://datatables.net/search/?cx=004673356914326163298%3Abcgejkcchl4&cof=FORID%3A9&ie=UTF-8&q=excel+formatting&sa=Search&siteurl=datatables.net%2Fforums%2F&ref=&ss=2970j745574j16).

Because the export is really just CSV there is no option to including colouring etc. It would require a lot of work to create a real Excel file that would support these options, and while I hope to do that in future, it likely isn't going to be for some time.
